[project]
name = "bomberman-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "pygame>=2.6.1",
    "scikit-learn>=1.9.0",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "tqdm>=4.70.0",
]
